# distance functions
@test edit_distance("AAAATTTTCCCCGGGG", "AAAATTATCCCCGGGG") == 1
@test edit_distance("AAAATTTTCCCCGGGG", "AAAATTTCCCCGGGG") == 1
@test edit_distance("AAAATTTTCCCCGGGG", "AAAATATCCCCGGGG") == 2
@test hamming_distance("AAAATTTTCCCCGGGG", "AAAATTATCCCCGGGG") == 1
@test hamming_distance("AAAATTTTCCCCGGGG", "AAAATTTCCCCGGGG") == 2

function test_merge()
    r1 = dna("CCACCCAAAGCCGCGGGCGCTGATGATGGGTGAGGAGGGGGCGGCAAGATTTCGGGCGCCCCTGCCCTGAACGCCCTCAGCTGCTGCCGCCGGGGCCGCTCCGGAGGCGGGAGCCGGTAGCCGAGCCGGGCGACCTAGAGAACGAGCG")
    r2 = dna("CACTTCATTCAGCGGACCGACAGAGTGGCCGACGCTGAGCCTGACCCGCTCGTTCTCTAGGTCGCCCGGCTCGGCTACCGGCTCCCGCCTCCGGAGCGGCCCCGGCGGCAGCAGCTGAGGGCGTTCAGGGCAGGGGCGCCCGAAATC")
    merged_truth = dna("CCACCCAAAGCCGCGGGCGCTGATGATGGGTGAGGAGGGGGCGGCAAGATTTCGGGCGCCCCTGCCCTGAACGCCCTCAGCTGCTGCCGCCGGGGCCGCTCCGGAGGCGGGAGCCGGTAGCCGAGCCGGGCGACCTAGAGAACGAGCGGGTCAGGCTCAGCGTCGGCCACTCTGTCGGTCCGCTGAATGAAGTG")
    return try_merge(r1, r2) == merged_truth
end

@test test_merge()